<?php
$this->headTitle('Create role');
?>
<div class="create-form">
<?php
echo $this->form()->openTag($form);
echo $this->tbFormRow($form->get('role_id'));
echo $this->tbFormRow($form->get('description'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/role'); ?>" class="btn btn-link"><?php echo $this->translate('Cancel'); ?></a>
<?php
echo $this->form()->closeTag();
?>
</div>