<?php
$this->headTitle('Edit role');
echo $this->partial('ht-admin/role/partial/tab-navigator', array(
    'activeTab' => 1,
    'role' => $role,
));
?>
<div class="create-form">
<?php
echo $this->message($this);
?>
    <div class="form-group"><?php echo $this->translate("Role id:"); ?>
        &nbsp;
        <strong><?php echo $this->escapeHtml($role->getRoleId()); ?></strong>
    </div>
<?php
echo $this->form()->openTag($form);
echo $this->tbFormRow($form->get('description'));
echo $this->formSubmit($form->get('submit')->setValue('Save'));
?>
<a href="<?php echo $this->url('admin/role'); ?>" class="btn btn-link">
    <?php echo $this->translate('Cancel'); ?>
</a>
<?php
echo $this->form()->closeTag();
?>
</div>