<?php
$this->headTitle($this->translate('Update server'));
?>
<h3 class="text-center"><?php echo $this->escapeHtml($server->getTitle()); ?></h3>
<div class="create-form">
    <?php
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('server_id'));
    echo $this->tbFormRow($form->get('title'));
    echo $this->tbFormRow($form->get('description'));
    echo $this->tbFormRow($form->get('ip'));
    echo $this->tbFormRow($form->get('location'));
    echo $this->tbFormRow($form->get('status'));
    echo $this->tbFormRow($form->get('domain'));
    ?>
    <div class="form-group has-feedback ">
        <p class="control-label" for="secret">
            <?php echo $this->translate('Secret: '); ?>
        </p>
        <input type="text" name="secret" readonly="readonly" class=" form-control" value="<?php echo $this->escapeHtmlAttr($server->getSecret()); ?>">
    </div>
    <div class="control-group">
        <label class="control-label"></label>
        <div class="controls">
            <?php echo $this->formSubmit($form->get('submit')); ?>
            <a class="btn" href="<?php echo $this->url('admin/server'); ?>"><?php echo $this->translate('Cancel'); ?></a>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>
<?php $this->inlineScript()->appendFile($this->basePath('js/custom/create-server.js')); ?>
<?php $this->inlineScript()->appendScript(<<<END
        $(document).ready(function () {
            $('[name="secret"]').on('click',function () {
                $(this).select();
            });
        });
END
);