<?php
echo $this->partial('partial/tab', array('tabs' => array(
	array(
		'name' => $this->translate('General Info'),
		'url' => $this->url('admin/org/common', 
				array('action' => 'edit', 'id' => $organisationId)
				),
		'isActive' => ($activeTab == 1)
	),
	array(
		'name' => $this->translate('Applications'),
		'url' => $this->url('admin/org/app', array('id' => $organisationId)),
		'isActive' => ($activeTab == 2)
	),
	array(
		'name' => $this->translate('Users'),
		'url' => $this->url('admin/org/user', array('id' => $organisationId)),
		'isActive' => ($activeTab == 3)
	)
)));
?>