<?php
$this->headTitle(sprintf($this->translate('%s - User Management'), $application->getTitle()));

echo $this->message($this); ?>
<script type="text/javascript">
	var applicationId = <?php echo $application->getApplicationId(); ?>
</script>
<h3 class="text-center"><?php echo sprintf($this->translate('%s Application'), $this->escapeHtml($application->getTitle()));?></h3>
<?php
echo $this->partial('ht-admin/application/partial/tab-navigator.phtml', array(
	'appId' => $application->getApplicationId(),
	'activeTab' => 3,
));
?>
<form class="form-inline" method="post" action="<?php echo $this->url('admin/user-application',
		array('action' => 'add-user', 'id' => $application->getApplicationId())); ?>">
	<table class="table">
		<tbody>
			<tr>
				<td>
					<input type="text" name="user_id" placeholder="<?php echo $this->translate('Firstname, lastname or email'); ?>" >
				</td>
				<td>
					<select style="width:100%;" class="form-control" name="organisation_id" disabled="disabled">
						<option><?php echo $this->translate('Input an user.'); ?></option>
					</select>
				</td>
				<td>
					<select style="width:100%;" class="form-control" name="server_id" disabled="disabled">
						<option><?php echo $this->translate('Select an organistion'); ?></option>
					</select>
					<i class="fa fa-spinner fa-spin" id="icon-loading" style="display: none;"></i>
				</td>
				<td class="text-center">
					<button class="btn btn-link" type="submit">
						<i class="fa fa-plus-circle fa-lg icon-add"></i>
					</button>
				</td>
			</tr>
		</tbody>
	</table>
</form>

<?php if ($totalUsers > 0) {
		echo $this->partial('partial/confirm-modal', array('title' => $this->translate('Delete user')));
	?>
<table class="table table-striped">
	<tbody>
		<?php
		foreach ($users as $user) {
			$name = $user->firstname . ' ' . $user->lastname;
            $confirmMessage = sprintf(
                    $this->translate('Are you sure you want to delete <b>%s</b>?<br />You will not be able to undo this action.'),
                    $this->escapeHtmlAttr($name)
                    );
		?>
		<tr>
			<td>
				<?php echo $this->escapeHtml($name); ?>
			</td>
			<td>
				<?php echo $this->escapeHtml($user->org_title); ?>
			</td>
			<td>
				<?php echo $this->escapeHtml($user->server_title); ?>
			</td>
			<td class="text-center">
				<a class="btn btn-link" 
				   data-confirm-message="<?php echo $confirmMessage; ?>"
				   href="<?php echo $this->url('admin/user-application',
							array('action' => 'delete-user', 'id' => $user->user_application_id));
					?>">
					<i class="fa fa-times fa-lg icon-remove"></i>
				</a>
			</td>
		</tr>
		<?php } ?>
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'partial/pagination-control', array('route' => null));
} else { ?>
<table class="table table-striped">
	<tr>
		<td class="text-center">
		<?php echo $this->translate('No user found.'); ?>
		</td>
	</tr>
</table>
<?php }
$this->inlineScript()->appendFile($this->basePath('js/custom/application-add-user.js'));
?>