<!--<div class="create-form">-->
<?php
$this->headTitle(sprintf($this->translate('%s Organisation'), $organisation->getTitle()));
?>
	<h3 class="text-center"><?php echo sprintf($this->translate('%s Organisation'), $organisation->getTitle()); ?></h3>
	<?php
	echo $this->partial('ht-admin/organisation/partial/tab-navigator.phtml', array(
		'organisationId' => $organisation->getOrganisationId(),
		'activeTab' => 1,
	));
	?>
	<div class="tab-content">
		<?php
		$form->prepare();
		echo $this->form()->openTag($form);
		echo $this->formHidden($form->get('organisation_id'));
		echo $this->tbFormRow($form->get('title'));
		echo $this->tbFormRow($form->get('description'));
		echo $this->tbFormRow($form->get('domain'));
		?>
		<div class="control-group">
			<label class="control-label"></label>
			<div class="controls">
				<?php echo $this->formSubmit($form->get('submit')); ?>
				<a class="btn" href="<?php echo $this->url('admin/org'); ?>"><?php echo $this->translate('Cancel'); ?></a>
			</div>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
<!--</div>-->