<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'HtUser\Module'                                 => __DIR__ . '/Module.php',
  'HtUser\Controller\AccessController'            => __DIR__ . '/src/HtUser/Controller/AccessController.php',
  'HtUser\Controller\InviteController'            => __DIR__ . '/src/HtUser/Controller/InviteController.php',
  'HtUser\Controller\ProfileController'           => __DIR__ . '/src/HtUser/Controller/ProfileController.php',
  'HtUser\Form\InviteActivate'                    => __DIR__ . '/src/HtUser/Form/InviteActivate.php',
  'HtUser\Form\InviteActivateFilter'              => __DIR__ . '/src/HtUser/Form/InviteActivateFilter.php',
  'HtUser\Model\ApplicationInvite'                => __DIR__ . '/src/HtUser/Model/ApplicationInvite.php',
  'HtUser\Model\ApplicationInviteTable'           => __DIR__ . '/src/HtUser/Model/ApplicationInviteTable.php',
  'HtUser\Model\Invite'                           => __DIR__ . '/src/HtUser/Model/Invite.php',
  'HtUser\Model\InviteTable'                      => __DIR__ . '/src/HtUser/Model/InviteTable.php',
  'HtUser\Model\User'                             => __DIR__ . '/src/HtUser/Model/User.php',
  'HtUser\Model\UserCollection'                   => __DIR__ . '/src/HtUser/Model/UserCollection.php',
  'HtUser\Model\UserTable'                        => __DIR__ . '/src/HtUser/Model/UserTable.php',
  'HtUser\Service\Model\ApplicationInviteFactory' => __DIR__ . '/src/HtUser/Service/Model/ApplicationInviteFactory.php',
  'HtUser\Service\Model\InviteFactory'            => __DIR__ . '/src/HtUser/Service/Model/InviteFactory.php',
  'HtUser\Service\Model\UserCollectionFactory'    => __DIR__ . '/src/HtUser/Service/Model/UserCollectionFactory.php',
  'HtUser\Service\Model\UserFactory'              => __DIR__ . '/src/HtUser/Service/Model/UserFactory.php',
  'HtUserTest\Bootstrap'                          => __DIR__ . '/test/Bootstrap.php',
  'HtUserTest\Controller\InviteControllerTest'    => __DIR__ . '/test/HtUserTest/Controller/InviteControllerTest.php',
  'HtUserTest\Model\UserDeleteTest'               => __DIR__ . '/test/HtUserTest/Model/UserDeleteTest.php',
);
