<?php $this->headTitle($organisation->getTitle() . $this->translate(' - Users management')); ?>
<?php echo $this->message($this); ?>
<script type="text/javascript">
	var organisationId = <?php echo $organisation->getOrganisationId(); ?>;
</script>
<h3 class="text-center"><?php echo $this->escapeHtml($organisation->getTitle()) . $this->translate(' Organisation'); ?></h3>
<?php
echo $this->partial('ht-admin/organisation/partial/tab-navigator.phtml',array(
	'organisationId' => $organisation->getOrganisationId(),
	'activeTab' => 3,
));
?>
<form class="form-inline" method="POST" action="<?php echo $this->url('admin/user-organisation', 
		array('action' => 'add-user', 'id' => $organisation->getOrganisationId())); ?>">
	<table class="table">
		<tbody>
			<tr>
				<td>
					<input type="text" name="user_id" placeholder="<?php echo $this->translate('Name'); ?>" >
				</td>
				<td class="text-center">
					<button class="btn btn-link" type="submit">
						<i class="fa fa-plus-circle fa-lg icon-add"></i>
					</button>
				</td>
			</tr>
		</tbody>
	</table>
</form>
<?php if ($totalUsers > 0) { ?>
	
<!-- Modal -->
<?php
    echo $this->partial('partial/confirm-modal', array('title' => $this->translate('Delete user')));
?>
<!-- end Modal -->
	
<table class="table table-striped">
	<tbody>
		<?php foreach ($users as $user) {
            $name = $user->firstname . ' ' . $user->lastname;
            $confirmMessage = sprintf(
                    $this->translate('Are you sure you want to delete <b>%s</b>?<br />You will not be able to undo this action.'),
                    $this->escapeHtmlAttr($name)
                    );
        ?>
		<tr>
			<td>
				<?php echo $this->escapeHtml($name); ?>
			</td>
			<td>
				<?php echo $this->escapeHtml($user->email); ?>
			</td>
			<td class="text-center">
				<a class="btn btn-link" 
				   data-confirm-message="<?php echo $confirmMessage; ?>"
				   href="<?php echo $this->url('admin/user-organisation',
							array('action' => 'delete-user', 'id' => $user->user_organisation_id));
					?>">
					<i class="fa fa-times fa-lg icon-remove"></i>
				</a>
			</td>
		</tr>
		<?php } ?>
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination-control', array('route' => null)); ?>
<?php } else {?>
<table class="table table-striped">
	<tbody>
		<tr>
			<td class="text-center">
				<?php echo $this->translate('No user found.'); ?>
			</td>
		</tr>
	</tbody>
</table>
<?php } ?>

<?php $this->inlineScript()->appendFile($this->basePath('js/custom/organisation-add-user.js'));
?>

