<?php
$this->headTitle($this->translate('Log details'));
?>
<h3 class="text-center"><?php echo $this->translate('Log details'); ?></h3>
<div class="col-lg-6 col-lg-offset-3">
<table class="table">
    <tr>
        <td class="col-sm-4"><?php echo $this->translate('Ip address: '); ?></td>
        <td><?php echo $this->escapeHtml($log->getIpAddress()); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->translate('User: '); ?></td>
        <td><?php echo $this->escapeHtml($user->getName()); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Event:'); ?></td>
        <td><?php echo $this->escapeHtml($log->getTypeName()); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Time:'); ?></td>
        <td><?php echo $this->escapeHtml($log->getTime()); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Log type:') ?></td>
        <td><?php echo $this->escapeHtml($log->getLogType(true)); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Message:') ?></td>
        <td><?php echo $this->escapeHtml($log->getMessage()); ?></td>
    </tr>
</table>
</div>
<div class="col-lg-12 text-center">
    <a href="<?php echo $backUrl; ?>" class="btn btn-default">
        <?php echo $this->translate('Back'); ?>
    </a>
</div>