<?php
$this->headTitle($server->getTitle());
echo $this->message($this);
?>
<h3 class="text-center"><?php echo $this->escapeHtml($server->getTitle()); ?></h3>
<?php
echo $this->partial('ht-admin/server/partial/tab-navigator', array('serverId' => $server->getServerId(), 'activeTab' => 2));
?>
<?php if ($totalOrgs > 0) { ?>
    <!-- Modal -->
    <?php
    echo $this->partial('partial/confirm-modal', array(
        'title' => $this->translate('Delete user'),
        'message' => $this->translate('Are you sure you want to delete <b>%replace_string%</b>?'
                . '<br />You will not be able to undo this action.'),
    ));
    ?>
    <!-- end Modal -->
    <table class="table table-striped">
        <tbody>
            <?php
            foreach ($organisations as $organisation) {
                ?>
                <tr>
                    <td>
                        <?php echo $this->escapeHtml($organisation->title); ?>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
    <?php
    echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination-control', array('route' => null));
} else {
    ?>
    <table class="table table-striped">
        <tbody>
            <tr>
                <td class="text-center"><?php echo $this->translate('No organisation found.'); ?></td>
            </tr>
        </tbody>
    </table>
<?php } ?>