<?php $this->headTitle($this->translate('Login')); ?>
<div class='form-signin'>
	<h3 class="form-signin-heading"><?php echo $this->translate("Log in"); ?></h3>
	<div class="btn-group">
		<a class="btn btn-default" href="<?php echo $this->url('oauth', array('action' => 'login', 'provider' => 'facebook')); ?>">
			<i class="fa fa-facebook-square fa-lg"></i>&nbsp; <?php echo $this->translate('With Facebook') ?>
		</a>
		<a style="float: right;" class="btn btn-default" href="<?php echo $this->url('oauth', array('action' => 'login', 'provider' => 'google')); ?>">
			<i class="fa fa-google-plus-square fa-lg"></i>&nbsp; <?php echo $this->translate('With Google') ?> &nbsp;
		</a>
	</div>
	<div class="separator text-center">
		<h3><?php echo $this->translate('Or')?></h3>
	</div>
    <?php if ($errorMessage) { ?>
	<div class="alert alert-warning">
		<?php echo $errorMessage; ?>
	</div>
    <?php } ?>
    <div>
        <div class='form-signin' ng-controller="LoginController">
            <form novalidate method="post" name="form" id="login" action="/login" ng-submit="submit($event)">
                <div class="form-group has-feedback" ng-class="{ 'has-error': form.email.$invalid && form.email.$dirty }">
                    <input
                        type="email"
                        name="email"
                        placeholder="<?php echo $this->translate("Email address"); ?>"
                        class="form-control"
                        required="required"
                        value=""
                        ng-model="identity.email"
                        ng-change="change()"
                        ng-disabled="status.loading"
                        ng-model-options="{ updateOn: 'blur' }"
                    />
                    <span class="fa fa-times form-control-feedback" aria-hidden="true" ng-show="form.email.$dirty && form.email.$invalid" ng-cloak=""></span>
                    <span class="help-block" ng-show="form.email.$dirty && form.email.$error.required" ng-cloak>Email is required for login</span>
                    <span class="help-block" ng-show="form.email.$error.email" ng-cloak>Not a valid email</span>
                </div>
                <div class="form-group has-feedback" ng-class="{ 'has-error': form.password.$invalid && form.password.$dirty }">
                    <input
                        type="password"
                        name="password"
                        placeholder="<?php echo $this->translate("Password"); ?>"
                        class="form-control"
                        size="30"
                        required="required"
                        value=""
                        ng-model="identity.password"
                        ng-change="change()"
                        ng-disabled="status.loading"
                        ng-model-options="{ updateOn: 'blur' }"
                    />
                    <span class="fa fa-times form-control-feedback" aria-hidden="true" ng-show="form.password.$dirty && form.password.$invalid" ng-cloak=""></span>
                    <span class="help-block" ng-show="form.password.$dirty && form.password.$error.required" ng-cloak>Password is required for login</span>
                </div>
                <div class="checkbox">
                    <label>
                        <input
                            type="checkbox"
                            name="remember"
                            value="1"
                            ng-model="identity.remember"
                            ng-disabled="status.loading"
                        />
                        &nbsp;<?php echo $this->translate("Remember me"); ?>
                    </label>
                </div>
                <button name="submit" type="submit" class="btn btn-primary btn-lg btn-block" id="submitbutton" ng-disabled="status.loading">
                    <span class="hide" ng-class="{ 'show' : status.loading }">
                        <i class="fa fa-spinner fa-spin"></i>
                    </span>
                    <span ng-show="!status.loading && !status.success"><?php echo $this->translate("Login"); ?></span>
                    <span class="hide" ng-class="{ 'show' : status.success }">
                        <?php echo $this->translate("Successful!"); ?>
                    </span>
                </button>
                <div class="alert alert-danger" ng-show="status.loginError && !status.change" ng-cloak style="margin-top:10px;">{{ message }}</div>
            </form>
        </div>
    </div>
	<h5 class="text-center">
            <?php echo $this->translate('Need an account?'); ?>
            <a href="<?php echo $this->url('register'); ?>">
                <strong><?php echo $this->translate('Sign up for free.'); ?></strong>
            </a>
        </h5>
</div>
<?php
$this->inlineScript()->appendFile($this->basePath('lib/angular/angular.min.js'));
$this->inlineScript()->appendFile($this->basePath('js/custom-angularjs/login.js'));