<div class="create-form">
    <?php
    echo $this->headTitle($this->translate("Add Internal Login"));
    $this->inlineScript()->appendFile($this->basePath('js/custom/register.js', 'text/javascript'));
    ?>
    <h3 class="text-center"><?php echo $this->translate("Change Password"); ?></h3>
    <?php
    if (!empty($successMessage)) {
        ?>
        <div class="alert alert-success">
            <?php echo $successMessage; ?>
        </div>
        <?php
    } else {
        if ($errorMessage) {
            ?>
            <div class="alert alert-danger">
                <?php echo $errorMessage; ?>
            </div>
        <?php }
    }
    ?>
    <?php
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->tbFormRow($form->get('current_password'));
    echo $this->tbFormRow($form->get('password'));
    echo $this->tbFormRow($form->get('password_confirm'));
    ?>
    <div class="control-group">
        <label class="control-label"></label>
        <div class="controls">
<?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>
</div>