<?php
$this->inlineScript()->appendFile($this->basePath('js/custom/confirm.js'), 'text/javascript');
if (empty($message)) {
    /* %message% will replaced by attribute data-confirm-message */
    $message = '%message%';
}

if (empty($title)) {
    $title = $this->translate('Confirm');
}

if (empty($btnDismiss)) {
	$btnDismiss = $this->translate('Cancel');
}

if (empty($btnConfirm)) {
	$btnConfirm =  $this->translate('Confirm');
}
?>
<div id="modal-confirm" class="modal fade"  tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h3><?php echo $title; ?></h3>
			</div>
			<div class="modal-body">
				<p><?php echo $message; ?></p>
			</div>
			<div class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $btnDismiss;?></button>
				<button id="btn-confirm-ok" class="btn btn-primary"><?php echo $btnConfirm; ?></button>
			</div>
		</div>
	</div>
</div>