<?php
//@link https://raw.githubusercontent.com/fabiopaiva/zf2-navigation-bootstrap3/master/navigation.phtml
/* @var $container Zend\Navigation\Navigation */
$container = $this->container;
?>
<ul class="<?php echo $this->navigation()->menu()->getUlClass(); ?>">
    <?php foreach ($container as $page) { ?>
        <?php if (!$this->navigation()->accept($page)) {continue;} ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if (!$hasChildren) { ?>
            <li<?php if ($page->isActive()) echo ' class="active"' ?>>
                <a 
                    class="nav-header" 
                    href="<?php echo $page->getHref() ?>"
                    <?php if ($page->getTarget() != "") { ?>
                        target="<?php echo $page->getTarget(); ?>"
                    <?php  } ?>
                    >
                        <?php if ($page->get("icon") !== "") { ?>
                        <span class="<?php echo $page->get("icon"); ?>"></span>
                    <?php } ?>
                    <?php echo $page->getLabel() ?>
                </a>
            </li>
        <?php } else { ?>
            <?php
            //check if access is allowed at least one item
            $access = false;
            foreach ($page->getPages() as $child) {
                if ($this->navigation()->accept($child) && $child->get("separator") !== true) {
                    $access = true;
                }
            }
            if ($access) {
                ?>
                <li class="dropdown<?php if ($page->isActive(true)) echo ' active' ?>">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <?php if ($page->get("icon") !== "") { ?>
                            <span class="<?php echo $page->get("icon"); ?>"></span>
                        <?php } ?>
                        <?php echo $page->getLabel() ?>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <?php foreach ($page->getPages() as $child) { ?>
                            <?php if (!$this->navigation()->accept($child)) {continue; }?>
                            <?php if ($child->get("separator") === true) { ?>
                                <li class="divider"></li>
                                    <?php
                                    continue;
                                }
                                ?>
                            <li<?php if ($child->isActive(true)) echo ' class="active"' ?>>
                                <a 
                                    href="<?php echo $child->getHref() ?>"
                                    <?php if ($child->getTarget() != "") { ?>
                                        target="<?php echo $child->getTarget(); ?>"
                                    <?php } ?> >
                                        <?php if ($child->get("icon") !== "") { ?>
                                        <span class="<?php echo $child->get("icon"); ?>"></span>
                                        <?php } ?>
                                    <?php echo $child->getLabel() ?>
                                </a>
                            </li>
                        <?php } ?>
                    </ul>
                </li>   
            <?php } ?>
        <?php } ?>
    <?php } ?>
</ul>