<div class="container-fluid">
    <div class="navbar-header">
        <a href="/" class="payroll-logo" title="<?php echo $this->translate("Payroll Guru"); ?>"></a>
    </div>
    <div class="navbar-collapse collapse">            
        <?php
        if (isset($identity)) {
            if (is_object($identity)) {
                switch ($identity->authenticationProvider) {
                    case "internal":
                        /* $identity has property (userId, firstName, lastName, email, authenticationProvider, isEnabled) */
                        $name = $identity->firstName . ' ' . $identity->lastName;
                        $name = trim($name);
                        $name = $this->escapeHtml($name);
                        if (empty($name)) {
                            $name = $identity->email;
                        }
                        break;
                    case "facebook":
                        $name = "<img src='https://graph.facebook.com/" . $identity->oauthProviderId . "/picture'>";
                        break;
                    case "google":
                        if (!empty($identity->oauthProfile->picture)) {
                            $name = '<img src="' . $identity->oauthProfile->picture . '?sz=50"/>';
                        }
                    default:
                        break;
                }
            } elseif (is_string($identity)) {
                $name = $identity;
            }
            ?>
            <ul class="nav navbar-nav navbar-right admin-bar-my-account">
                <li>
                    <a id="app-btn" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="true">
                        <span class="application-icon"></span>
                    </a>
                    <div class="dropdown-menu app-box" role="menu" aria-labelledby="app-btn">
                        <div class="panel">
                            <div class="col-xs-4 col-sm-4 col-md-4 text-center">
                                <a href="<?php echo isset($payrollUrl) ? $payrollUrl : '#' ?>" class="app-image payroll-button" target="_blank" title="Payroll"></a>
                            </div>
                            <div class="col-xs-4 col-sm-4 col-md-4 text-center">
                                <a href="http://www.easyemployer.com.au/" class="app-image eE-button" target="_blank" title="Easy Employer"></a>
                            </div>
                            <div class="col-xs-4 col-sm-4 col-md-4 text-center">
                                <a href="<?php echo $this->url('home'); ?>" class="app-image userfed-logo" target="_blank" title="User Federation"></a>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle user-avatar" data-toggle="dropdown" href="#"><span class=""></span>
                        <?php
//                        if (isset($name)) {
//                            echo sprintf($this->translate('Hello %s'), $name);
//                        }
                        ?>
                        <img class="img-circle" src="/image/admin-placeholder-img.png">
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="<?php echo $this->basePath("/internal/update"); ?>"><?php echo $this->translate('Change Password'); ?></a>
                        </li>
                        <li>
                            <a href="<?php echo $this->basePath("/logout"); ?>"><?php echo $this->translate("Logout"); ?></a>
                        </li>
                    </ul>
                </li>
            </ul>
        <?php } ?>
    </div>

</div>