<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'HtAdmin\Module'                                               => __DIR__ . '/Module.php',
  'HtAdmin\Controller\ApplicationController'                     => __DIR__ . '/src/HtAdmin/Controller/ApplicationController.php',
  'HtAdmin\Controller\ApplicationOrganisationController'         => __DIR__ . '/src/HtAdmin/Controller/ApplicationOrganisationController.php',
  'HtAdmin\Controller\LogController'                             => __DIR__ . '/src/HtAdmin/Controller/LogController.php',
  'HtAdmin\Controller\OrganisationController'                    => __DIR__ . '/src/HtAdmin/Controller/OrganisationController.php',
  'HtAdmin\Controller\UserApplicationController'                 => __DIR__ . '/src/HtAdmin/Controller/UserApplicationController.php',
  'HtAdmin\Controller\UserController'                            => __DIR__ . '/src/HtAdmin/Controller/UserController.php',
  'HtAdmin\Controller\UserOrganisationController'                => __DIR__ . '/src/HtAdmin/Controller/UserOrganisationController.php',
  'HtAdmin\Form\Application'                                     => __DIR__ . '/src/HtAdmin/Form/Application.php',
  'HtAdmin\Form\CreateUser'                                      => __DIR__ . '/src/HtAdmin/Form/CreateUser.php',
  'HtAdmin\Form\EditUser'                                        => __DIR__ . '/src/HtAdmin/Form/EditUser.php',
  'HtAdmin\Form\Organisation'                                    => __DIR__ . '/src/HtAdmin/Form/Organisation.php',
  'HtAdmin\Test\AbstractHttpControllerTestCase'                  => __DIR__ . '/src/HtAdmin/Test/AbstractHttpControllerTestCase.php',
  'HtAdminTest\Bootstrap'                                        => __DIR__ . '/test/Bootstrap.php',
  'HtAdminTest\Controller\ApplicationControllerTest'             => __DIR__ . '/test/HtAdminTest/Controller/ApplicationControllerTest.php',
  'HtAdminTest\Controller\ApplicationOrganisationControllerTest' => __DIR__ . '/test/HtAdminTest/Controller/ApplicationOrganisationControllerTest.php',
  'HtAdminTest\Controller\OrganisationControllerTest'            => __DIR__ . '/test/HtAdminTest/Controller/OrganisationControllerTest.php',
  'HtAdminTest\Controller\UserApplicationControllerTest'         => __DIR__ . '/test/HtAdminTest/Controller/UserApplicationControllerTest.php',
  'HtAdminTest\Controller\UserOrgnisationControllerTest'         => __DIR__ . '/test/HtAdminTest/Controller/UserOrgnisationControllerTest.php',
);
